## Use of face_recognition library

In [3]:
#loading of images and check for the image shape

import face_recognition
photo1 = face_recognition.load_image_file('./pics&group/pic1.jpeg','RGB')
photo2 = face_recognition.load_image_file('./pics&group/pic2.jpeg','RGB')
photo3 = face_recognition.load_image_file('./pics&group/pic3.jpeg')
print("The shapes of the Color photo files are...")
print("photo1 Photo....",photo1.shape)
print("photo2 Photo.....", photo2.shape)
print("photo3 Photo......", photo3.shape)

The shapes of the Color photo files are...
photo1 Photo.... (1024, 769, 3)
photo2 Photo..... (1024, 769, 3)
photo3 Photo...... (1024, 769, 3)


In [4]:
# we want to load the files in Black and White format we must use using 'L'
# attribute in the second attribute of load_image_file() function as follows:

photoA = face_recognition.load_image_file('./pics&group/pic1.jpeg','L')
photoB = face_recognition.load_image_file('./pics&group/pic2.jpeg','L')
photoC = face_recognition.load_image_file('./pics&group/pic3.jpeg', 'L')
print("The shapes of the bw photo files are...")
print("photoA Photo....",photoA.shape)
print("photoB Photo.....", photoB.shape)
print("photoC Photo......", photoC.shape)

The shapes of the bw photo files are...
photoA Photo.... (1024, 769)
photoB Photo..... (1024, 769)
photoC Photo...... (1024, 769)


## Python Image Library

Python Image Library (PIL) is a opensource library for Python that supports image processing
activities of pictures, including the display

In [5]:
from PIL import Image
import face_recognition
pil_image1 = Image.fromarray(photo1)
pil_image1.show()
pil_image2 = Image.fromarray(photo2)
pil_image2.show()
pil_image3 = Image.fromarray(photo3)
pil_image3.show()

In [6]:
pil_image1 = Image.fromarray(photoA)
pil_image1.show()
pil_image2 = Image.fromarray(photoB)
pil_image2.show()
pil_image3 = Image.fromarray(photoC)
pil_image3.show()

## Face Locations Method

In python face-recognition library, face_locations() method detects all human faces in the image.
Each face is detected as a rectangular frame in the form of a tuple (top,left,bottom,right). If there are n faces, the output is a list of n tuples with four entries as (top, right, bottom, left).

## HOG (Histogram Oriented Gradient) Approach.

In detecting the faces and locating the rectangular frames HOG (Histogram Oriented Gradient) Approach. This is faster but less accurate.

In [7]:
from PIL import Image
import face_recognition
test_pic3 = face_recognition.load_image_file('./pics&group/pic3.jpeg')
print(test_pic3.shape)
l = face_recognition.face_locations(test_pic3, model = 'hog')
print(l)
top = l[0][0]
right = l[0][1]
bottom = l[0][2]
left = l[0][3]
pic3_face = test_pic3[top:bottom, left:right]
print(test_pic3.shape)
pic3_face_image = Image.fromarray(pic3_face)
pic3_face_image.show()

(1024, 769, 3)
[(376, 546, 761, 161), (580, 184, 735, 29)]
(1024, 769, 3)


In [6]:
#Face Detection using HOG Model 

from PIL import Image
import face_recognition

# Load the jpg file into a numpy array
group_photo = face_recognition.load_image_file("./pics&group/group1.jpeg")

# Find all the faces in the image 
face_locations = face_recognition.face_locations(group_photo, model="hog")
# Let us print the number of faces in the Photo
print("There are  {} face(s) in this photo".format(len(face_locations)))
face_count = 0
for face_location in face_locations:
    # Print the location of each face in this image
    face_count = face_count+1
    top, right, bottom, left = face_location
    print("Face {}...Top: {}, Left: {}, Bottom: {}, Right: {}".format(face_count,top, left, bottom, right))
    # You can access the actual face itself like this:
    face_image = group_photo[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

There are  5 face(s) in this photo
Face 1...Top: 136, Left: 772, Bottom: 226, Right: 862
Face 2...Top: 130, Left: 536, Bottom: 204, Right: 610
Face 3...Top: 188, Left: 386, Bottom: 262, Right: 461
Face 4...Top: 175, Left: 223, Bottom: 218, Right: 266
Face 5...Top: 130, Left: 406, Bottom: 182, Right: 458


## Deep Learning based Convolution Neural Network (CNN) Approach.

CNN is more accurate but it takes more time to compute.

In [7]:
from PIL import Image
import face_recognition
test2_photo = face_recognition.load_image_file('./pics&group/pic3.jpeg')
print(test2_photo.shape)
l = face_recognition.face_locations(test2_photo, model ='cnn')
print(l)
top = l[0][0]
right = l[0][1]
bottom = l[0][2]
left = l[0][3]
test2_image = test2_photo[top:bottom, left:right]
print(test2_image.shape)
test2_face_image = Image.fromarray(test2_image)
test2_face_image.show()

(1024, 769, 3)
[(386, 506, 739, 154), (560, 196, 729, 26)]
(353, 352, 3)


In [8]:
# Deep Learning based Convolution Neural Network (CNN) approach. CNN
# is more accurate but it takes more time to compute.

from PIL import Image
import face_recognition

# Load the jpg file into a numpy array
group_photo = face_recognition.load_image_file("./pics&group/group1.jpeg")

# Find all the faces in the image 
face_locations = face_recognition.face_locations(group_photo, model="cnn")
# Let us print the number of faces in the Photo
print("There are  {} face(s) in this photo".format(len(face_locations)))
face_count = 0
for face_location in face_locations:
    # Print the location of each face in this image
    face_count = face_count+1
    top, right, bottom, left = face_location
    print("Face {}...Top: {}, Left: {}, Bottom: {}, Right: {}".format(face_count,top, left, bottom, right))
    # You can access the actual face itself like this:
    face_image = group_photo[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

There are  8 face(s) in this photo
Face 1...Top: 163, Left: 35, Bottom: 210, Right: 82
Face 2...Top: 135, Left: 783, Bottom: 203, Right: 852
Face 3...Top: 137, Left: 555, Bottom: 194, Right: 611
Face 4...Top: 183, Left: 376, Bottom: 252, Right: 444
Face 5...Top: 211, Left: 318, Bottom: 258, Right: 365
Face 6...Top: 173, Left: 217, Bottom: 220, Right: 264
Face 7...Top: 129, Left: 414, Bottom: 177, Right: 461
Face 8...Top: 177, Left: 884, Bottom: 225, Right: 932


In [9]:
group_photo = face_recognition.load_image_file("./pics&group/pic3.jpeg")

# Find all the faces in the image 
face_locations = face_recognition.face_locations(group_photo, model="cnn")
# Let us print the number of faces in the Photo
print("There are  {} face(s) in this photo".format(len(face_locations)))
face_count = 0
for face_location in face_locations:
    # Print the location of each face in this image
    face_count = face_count+1
    top, right, bottom, left = face_location
    print("Face {}...Top: {}, Left: {}, Bottom: {}, Right: {}".format(face_count,top, left, bottom, right))
    # You can access the actual face itself like this:
    face_image = group_photo[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

There are  2 face(s) in this photo
Face 1...Top: 386, Left: 154, Bottom: 739, Right: 506
Face 2...Top: 560, Left: 26, Bottom: 729, Right: 196


 ## Locate Faces and Mark with rectangle

In [16]:
from PIL import Image, ImageDraw
import face_recognition
test_photo = face_recognition.load_image_file('./pics&group/pic5.jpeg')
print(test_photo.shape)
l = face_recognition.face_locations(test_photo)
print(l)
top = l[0][0]
right = l[0][1]
bottom = l[0][2]
left = l[0][3]
test_face = test_photo[top:bottom, left:right]
print(test_face.shape)
test_face_image = Image.fromarray(test_face)
#text_face_image.show()
test_photo_image = Image.fromarray(test_photo)
draw = ImageDraw.Draw(test_photo_image)
draw.rectangle(
   (left, top, right, bottom),
   outline = (0, 0, 255), width = 5)
test_photo_image.show()

(1024, 769, 3)
[(333, 675, 718, 290)]
(385, 385, 3)


## Writing text on a Face Image

In [23]:
pip install art

Note: you may need to restart the kernel to use updated packages.Collecting art



In [8]:
from PIL import Image, ImageDraw, ImageFont
import face_recognition
photo_text = face_recognition.load_image_file('./pics&group/pic5.jpeg')
print(photo_text.shape)
l = face_recognition.face_locations(photo_text)
print(l)
top = l[0][0]
right = l[0][1]
bottom = l[0][2]
left = l[0][3]


#text_face_image.show()
text_photo_image = Image.fromarray(photo_text)
draw = ImageDraw.Draw(text_photo_image)
font = ImageFont.truetype("arial.ttf", 28, encoding="unic")
draw.rectangle(
   (left, top, right, bottom),
   outline=(0, 0, 255), width = 4)
draw.text((left+100,bottom - 50), "Text on Image", font=font, fill=(255,128,0))
text_photo_image.show()


(1024, 769, 3)
[(333, 675, 718, 290)]


## Locate all faces in a picture

In [9]:
from PIL import Image, ImageDraw
import face_recognition

# Load the jpg file into a numpy array
group_photo = face_recognition.load_image_file("./pics&group/group1.jpeg")

# Convert the group photo into a PIL Image
group_pil_image = Image.fromarray(group_photo)

# Find all the faces in the image 
fl = face_recognition.face_locations(group_photo, model = 'cnn')
draw = ImageDraw.Draw(group_pil_image)



# Let us print the number of faces in the Photo
face_count = len(fl)
print("No of Faces detected in this photo", face_count)

for i in range(face_count):
    # Print the location of each face in this image
    top, right, bottom, left = fl[i]
    print("Face,,", i, " Top, Left, , Bottom, Right..", top, left, bottom, right)
    # You can access the actual face itself like this:
    draw.rectangle(
            (left, top, right, bottom),
            outline=(255, 0, 0), width=3)
        
group_pil_image.show()


No of Faces detected in this photo 8
Face,, 0  Top, Left, , Bottom, Right.. 163 35 210 82
Face,, 1  Top, Left, , Bottom, Right.. 135 783 203 852
Face,, 2  Top, Left, , Bottom, Right.. 137 555 194 611
Face,, 3  Top, Left, , Bottom, Right.. 183 376 252 444
Face,, 4  Top, Left, , Bottom, Right.. 211 318 258 365
Face,, 5  Top, Left, , Bottom, Right.. 173 217 220 264
Face,, 6  Top, Left, , Bottom, Right.. 129 414 177 461
Face,, 7  Top, Left, , Bottom, Right.. 177 884 225 932


## Writing name on all faces

In [14]:
from PIL import Image, ImageDraw, ImageFont
import face_recognition

# Load the jpg file into a numpy array
grp_photo = face_recognition.load_image_file("./pics&group/group1.jpeg")

# Convert the group photo into a PIL Image
grp_pil_image = Image.fromarray(grp_photo)

# Find all the faces in the image 
fl = face_recognition.face_locations(grp_photo, model ='cnn')
# Let us print the number of faces in the Photo
face_count = len(fl)
print("No of Faces detected in this photo", face_count)

draw = ImageDraw.Draw(grp_pil_image)

fnt = ImageFont.truetype("calibri.ttf", 28, encoding="unic")
# Let us print the number of faces in the Photo

for i in range(face_count):
    # Print the location of each face in this image
    top, right, bottom, left = fl[i]
    print("Face,,", i, " Top, Left, , Bottom, Right..", top, left, bottom, right)
    # You can access the actual face itself like this:
    draw.rectangle(
            (left, top, right, bottom),
            outline=(255, 0, 0), width = 3)
    draw.text((left,bottom-20), str(i), font=fnt, fill=(0,0,255))   
grp_pil_image.show()


No of Faces detected in this photo 8
Face,, 0  Top, Left, , Bottom, Right.. 163 35 210 82
Face,, 1  Top, Left, , Bottom, Right.. 135 783 203 852
Face,, 2  Top, Left, , Bottom, Right.. 137 555 194 611
Face,, 3  Top, Left, , Bottom, Right.. 183 376 252 444
Face,, 4  Top, Left, , Bottom, Right.. 211 318 258 365
Face,, 5  Top, Left, , Bottom, Right.. 173 217 220 264
Face,, 6  Top, Left, , Bottom, Right.. 129 414 177 461
Face,, 7  Top, Left, , Bottom, Right.. 177 884 225 932


## Face encoding

In [18]:
#Program to load a picture and find its face encoding
import face_recognition
photo_emma = face_recognition.load_image_file('./pics&group/pic1.jpeg','RGB')
encodings_emma = face_recognition.face_encodings(photo_emma)[0]
print("The shapes of the Encoding array is ...", encodings_emma.shape)
print("Now let us print the encoding")
print(encodings_emma)

The shapes of the Encoding array is ... (128,)
Now let us print the encoding
[-2.11196303e-01  1.78484723e-01  1.11796908e-01 -3.69675346e-02
 -2.81905085e-02 -7.96913281e-02  2.95548178e-02 -6.80622309e-02
  1.18464306e-01  3.97704542e-02  2.61571705e-01 -4.08349298e-02
 -2.01663181e-01 -1.86527967e-01  1.27971441e-01  1.42350957e-01
 -1.49539962e-01 -7.07360655e-02 -5.49269170e-02 -1.37426510e-01
  1.79726519e-02  4.34840657e-02  4.31205854e-02  9.45459157e-02
 -3.19219604e-02 -4.02293891e-01 -8.23119879e-02 -1.75026685e-01
  9.38636884e-02 -8.30285996e-02  4.03862819e-02  1.10961404e-02
 -2.03860983e-01 -6.13673441e-02 -4.40345928e-02  1.05566584e-01
  2.47344486e-02 -2.93298531e-02  1.55784652e-01 -7.25218095e-04
 -8.27835128e-02 -4.86381724e-02 -2.85921860e-02  2.58049905e-01
  1.73459381e-01 -2.19700485e-02  8.15376416e-02  3.18488553e-02
  5.31721041e-02 -1.66757688e-01  1.08115096e-02  1.21095069e-01
  1.49202660e-01  3.57866846e-02 -2.72658207e-02 -1.29513174e-01
 -2.14305073e

In [19]:
import face_recognition
photo_gr = face_recognition.load_image_file('./pics&group/group1.jpeg','RGB')
encodings_gr = face_recognition.face_encodings(photo_gr)
print("The Number of faces  ...", len(encodings_gr))
print("The shape of each encodings..", encodings_gr[0].shape)
print("Now let us print the encoding")
for i in range(len(encodings_gr)):
    print(" Encodings of Face...", i)
    print(encodings_gr[i])

The Number of faces  ... 5
The shape of each encodings.. (128,)
Now let us print the encoding
 Encodings of Face... 0
[-0.16851413  0.10951909  0.09130862 -0.00648152 -0.04712614 -0.09275217
  0.11184111 -0.01224661  0.16049841  0.00345446  0.28697512 -0.0394378
 -0.19605157 -0.06900647  0.04252433  0.11760568 -0.16608121 -0.06631181
 -0.0669986  -0.16470782  0.01836197  0.03297566 -0.0607566   0.11454876
 -0.01997722 -0.27992588 -0.10438471 -0.18017244  0.08362632 -0.06120595
  0.07091173  0.04499901 -0.12710778 -0.100105   -0.02111205 -0.04602595
  0.05683868 -0.03351158  0.19145587  0.04520325 -0.08333259 -0.0273391
 -0.03052833  0.33285275  0.15645711 -0.02413912  0.04633876  0.03644516
  0.07724839 -0.19944479 -0.01383691  0.12738112  0.17862241  0.03740514
 -0.05250606 -0.12228778 -0.04824601  0.01925332 -0.21925557  0.035402
  0.09511295 -0.12231942 -0.11125809 -0.03407955  0.27352944  0.11860164
 -0.10853916 -0.2043923   0.20215978 -0.14921896 -0.05338492  0.08789917
 -0.173991

## Distance Function and Resemblance of Faces

The purpose of encoding is to find a unique signature for a face. If we consider two face photos of the same person and find out the encodings of each photo. The two encodings are almost same. This means that the Euclidean distance between them is as small as less than 0.6. If the two encodings are for two different person's photos, the distance is more than 0.6. 
People with resemblance have encodings with distances small and people with totally difference face appearances have encodings of distance high.

In [20]:
#Program to find distance between faces
import face_recognition
photo_recog1 = face_recognition.load_image_file('./pics&group/pic1.jpeg','RGB')
encodings_recog1 = face_recognition.face_encodings(photo_recog1)[0]

photo_recog2 = face_recognition.load_image_file('./pics&group/pic2.jpeg','RGB')
encodings_recog2 = face_recognition.face_encodings(photo_recog2)[0]
dist = face_recognition.face_distance([encodings_recog1],encodings_recog2)
print("Distance between the two photos ", dist)

Distance between the two photos  [0.40638764]


## Distance between multiple photos

In [21]:
#Program to load a picture and find its face encoding of same person
import face_recognition
fa = face_recognition.load_image_file('./pics&group/pic1.jpeg','RGB')
f0 = face_recognition.load_image_file('./pics&group/pic2.jpeg','RGB')
f1 = face_recognition.load_image_file('./pics&group/pic3.jpeg','RGB')
f2 = face_recognition.load_image_file('./pics&group/pic4.jpeg','RGB')
f3 = face_recognition.load_image_file('./pics&group/pic5.jpeg','RGB')

fa_sign = face_recognition.face_encodings(fa)[0]
f0_sign = face_recognition.face_encodings(f0)[0]
f1_sign = face_recognition.face_encodings(f1)[0]
f2_sign = face_recognition.face_encodings(f2)[0]
f3_sign = face_recognition.face_encodings(f3)[0]


faces = [f0_sign, f1_sign, f2_sign, f3_sign ]
dist = face_recognition.face_distance(faces,fa_sign)
print("Distance: pic1 to pic2, pic3, pic4,  and pic5 respectively")
print(dist)

Distance: pic1 to pic2, pic3, pic4,  and pic5 respectively
[0.40638764 0.38324746 0.32724422 0.41067434]


In [23]:
#Program to load five photos of different person
import face_recognition
#Load the five photos of the different person
celebrit1 = face_recognition.load_image_file('./face_recog/celebrit1.jpg','RGB')
celebrit2 = face_recognition.load_image_file('./face_recog/celebrit2.jpg','RGB')
celebrit3 = face_recognition.load_image_file('./face_recog/celebrit3.jpg','RGB')
celebrit4 = face_recognition.load_image_file('./face_recog/celebrit4.jpg','RGB')
celebrit5 = face_recognition.load_image_file('./face_recog/celebrit5.jpg','RGB')

#Let us find the encodings for each of the five faces
encodings_celebrit1 = face_recognition.face_encodings(celebrit1)[0]
encodings_celebrit2 = face_recognition.face_encodings(celebrit2)[0]
encodings_celebrit3 = face_recognition.face_encodings(celebrit3)[0]
encodings_celebrit4 = face_recognition.face_encodings(celebrit4)[0]
encodings_celebrit5 = face_recognition.face_encodings(celebrit5)[0]

# Let us find the distances between faces
dist01_02 = face_recognition.face_distance([encodings_celebrit1],encodings_celebrit2)
dist02_03 = face_recognition.face_distance([encodings_celebrit2],encodings_celebrit3)
dist03_04 = face_recognition.face_distance([encodings_celebrit3],encodings_celebrit4)
dist04_05 = face_recognition.face_distance([encodings_celebrit4],encodings_celebrit5)
dist05_01 = face_recognition.face_distance([encodings_celebrit5],encodings_celebrit1)
print("Distance 1 to 2 ", dist01_02)
print("Distance 2 to 3 ", dist02_03)
print("Distance 3 to 4 ", dist03_04)
print("Distance 4 to 5 ", dist04_05)
print("Distance 5 to 1 ", dist05_01)

Distance 1 to 2  [0.6686964]
Distance 2 to 3  [0.71448367]
Distance 3 to 4  [0.78403007]
Distance 4 to 5  [0.89384318]
Distance 5 to 1  [0.89317529]


## Face mapping

In [69]:
#Father to Son face mapping
# Python program to recognize the photo of a son and map to
# the father depending upon the resemblance.

import face_recognition
n = 6
photo_father =[]
encodings_father = []
photo_son = []
encodings_son = []
for i in range(n):
    f_path_template = './father/father0{}.png'
    f_path = f_path_template.format(i)
    photo_father.append(face_recognition.load_image_file(f_path,'RGB'))
    encodings_father.append(face_recognition.face_encodings(photo_father[i])[0])
    
    s_path_template = './son/son0{}.png'
    s_path = s_path_template.format(i)
    photo_son.append(face_recognition.load_image_file(s_path,'RGB'))
    encodings_son.append(face_recognition.face_encodings(photo_son[i])[0])
    
for i in range(6):
    a = "\nDistance: Son {} to Fathers 0, 1, 2, 3, 4, 5"
    print(a.format(i))
    print(face_recognition.face_distance(encodings_father, encodings_son[i]))


Distance: Son 0 to Fathers 0, 1, 2, 3, 4, 5
[0.72990638 0.79360617 0.74602903 0.70046816 0.83568435 0.93820042]

Distance: Son 1 to Fathers 0, 1, 2, 3, 4, 5
[0.68449085 0.67372911 0.7230144  0.66845835 0.7651907  0.82157798]

Distance: Son 2 to Fathers 0, 1, 2, 3, 4, 5
[0.84429839 0.7744297  0.71290187 0.80236541 0.78670347 0.88211748]

Distance: Son 3 to Fathers 0, 1, 2, 3, 4, 5
[0.77117768 0.81288294 0.77629569 0.68695563 0.84930817 0.98030858]

Distance: Son 4 to Fathers 0, 1, 2, 3, 4, 5
[0.77196765 0.80404854 0.86240018 0.87669905 0.64447716 0.77138433]

Distance: Son 5 to Fathers 0, 1, 2, 3, 4, 5
[0.84356954 0.83386023 0.83312569 0.81627252 0.80699236 0.73860243]


## Face Recognition – Compare method

In this method, compare_ faces() is used to
compare faces and recognize the faces.

The input parameters are:
1. A list of known face encodings
2. One unknown face encoding
The unknown face is compared with each of the known face fi in the List and a
Boolean value found(i) is created whether they match or not. The Boolean list found is
returned.

In [70]:
import face_recognition
image_emman = face_recognition.load_image_file('./pics&group/pic1.jpeg')
emman_encod = face_recognition.face_encodings(image_emman)[0]

image_em = face_recognition.load_image_file('./pics&group/pic5.jpeg')
em_encod = face_recognition.face_encodings(image_em)[0]
results = face_recognition.compare_faces([emman_encod], em_encod, tolerance = 0.5)
if results[0]:
    print("This is Emmanuel ")
else:
    print('This is NOT Emmanuel ')

This is Emmanuel 


In [71]:
import face_recognition
image_emman = face_recognition.load_image_file('./pics&group/pic1.jpeg')
emman_encod = face_recognition.face_encodings(image_emman)[0]

image_em = face_recognition.load_image_file('./pics&group/pic6.jpeg')
em_encod = face_recognition.face_encodings(image_em)[0]
results = face_recognition.compare_faces([emman_encod], em_encod, tolerance = 0.5)
if results[0]:
    print("This is Emmanuel ")
else:
    print('This is NOT Emmanuel ')

This is NOT Emmanuel 


## Face compare among unknown pictures

In [81]:
import face_recognition
pict_1 = face_recognition.load_image_file('./face_recog/celebrit1.jpg','RGB')
pict_2 = face_recognition.load_image_file('./face_recog/celebrit2.jpg','RGB')
pict_3 = face_recognition.load_image_file('./face_recog/celebrit3.jpg','RGB')
pict_4 = face_recognition.load_image_file('./face_recog/celebrit4.jpg','RGB')
pict_5 = face_recognition.load_image_file('./face_recog/celebrit5.jpg','RGB')
pict_6 = face_recognition.load_image_file('./face_recog/pic3.jpeg','RGB')
pict_unkwn = face_recognition.load_image_file('./pics&group/unknown.jpeg','RGB')

pict_unkwn_sign = face_recognition.face_encodings(pict_unkwn)[0]
pict1_sign = face_recognition.face_encodings(pict_1)[0]
pict2_sign = face_recognition.face_encodings(pict_2)[0]
pict3_sign = face_recognition.face_encodings(pict_3)[0]
pict4_sign = face_recognition.face_encodings(pict_4)[0]
pict5_sign = face_recognition.face_encodings(pict_5)[0]
pict6_sign = face_recognition.face_encodings(pict_6)[0]

faces = [pict1_sign, pict2_sign, pict3_sign, pict4_sign, pict5_sign, pict6_sign ]

compare_fnd = face_recognition.compare_faces(faces,pict_unkwn_sign, tolerance = 0.4)

print("Compare Matches:pict1, pict2, pict3, pict4, pict5, pict6")
print(compare_fnd)

Compare Matches:pict1, pict2, pict3, pict4, pict5, pict6
[False, False, False, False, False, True]


In [80]:
import face_recognition
pict_1 = face_recognition.load_image_file('./face_recog/celebrit1.jpg','RGB')
pict_2 = face_recognition.load_image_file('./face_recog/celebrit2.jpg','RGB')
pict_3 = face_recognition.load_image_file('./face_recog/celebrit3.jpg','RGB')
pict_4 = face_recognition.load_image_file('./face_recog/celebrit4.jpg','RGB')
pict_5 = face_recognition.load_image_file('./face_recog/celebrit5.jpg','RGB')
pict_6 = face_recognition.load_image_file('./face_recog/pic3.jpeg','RGB')
pict_unkwn = face_recognition.load_image_file('./pics&group/pic6.jpeg','RGB')

pict_unkwn_sign = face_recognition.face_encodings(pict_unkwn)[0]
pict1_sign = face_recognition.face_encodings(pict_1)[0]
pict2_sign = face_recognition.face_encodings(pict_2)[0]
pict3_sign = face_recognition.face_encodings(pict_3)[0]
pict4_sign = face_recognition.face_encodings(pict_4)[0]
pict5_sign = face_recognition.face_encodings(pict_5)[0]
pict6_sign = face_recognition.face_encodings(pict_6)[0]

faces = [pict1_sign, pict2_sign, pict3_sign, pict4_sign, pict5_sign, pict6_sign ]

compare_fnd = face_recognition.compare_faces(faces,pict_unkwn_sign, tolerance = 0.4)

print("Compare Matches:pict1, pict2, pict3, pict4, pict5, pict6")
print(compare_fnd)

Compare Matches:pict1, pict2, pict3, pict4, pict5, pict6
[False, False, False, False, False, False]


In [83]:
import face_recognition
pict_1 = face_recognition.load_image_file('./pics&group/pic1.jpeg','RGB')
pict_2 = face_recognition.load_image_file('./pics&group/pic2.jpeg','RGB')
pict_3 = face_recognition.load_image_file('./pics&group/pic3.jpeg','RGB')
pict_4 = face_recognition.load_image_file('./pics&group/pic4.jpeg','RGB')
pict_5 = face_recognition.load_image_file('./pics&group/pic5.jpeg','RGB')
pict_6 = face_recognition.load_image_file('./pics&group/pic6.jpeg','RGB')
pict_unkwn = face_recognition.load_image_file('./pics&group/unknown.jpeg','RGB')

pict_unkwn_sign = face_recognition.face_encodings(pict_unkwn)[0]
pict1_sign = face_recognition.face_encodings(pict_1)[0]
pict2_sign = face_recognition.face_encodings(pict_2)[0]
pict3_sign = face_recognition.face_encodings(pict_3)[0]
pict4_sign = face_recognition.face_encodings(pict_4)[0]
pict5_sign = face_recognition.face_encodings(pict_5)[0]
pict6_sign = face_recognition.face_encodings(pict_6)[0]

faces = [pict1_sign, pict2_sign, pict3_sign, pict4_sign, pict5_sign, pict6_sign ]

compare_fnd = face_recognition.compare_faces(faces,pict_unkwn_sign, tolerance = 0.4)

print("Compare Matches:pict1, pict2, pict3, pict4, pict5, pict6")
print(compare_fnd)

Compare Matches:pict1, pict2, pict3, pict4, pict5, pict6
[True, True, True, True, True, False]


## Image Data storage and compare using Python Pandas CSV File

In [87]:
import pandas as pd
import face_recognition
f = pd.read_csv('./Data.csv')
print(f.to_string())
empno = f["Staff_ID"].tolist()
name = f["Name"].tolist()
filename = f["File Name"].tolist()
n = len(empno)
emp = []
emp_encod = []
ukwn= face_recognition.load_image_file("./pics&group/pic1.jpeg")
ukwn_encod = face_recognition.face_encodings(ukwn)[0]
for i in range(n):
    emp.append(face_recognition.load_image_file(filename[i]))
    emp_encod.append(face_recognition.face_encodings(emp[i])[0])
found = face_recognition.compare_faces(emp_encod, ukwn_encod, tolerance = 0.5)    

print(found)

   Staff_ID         Name                   File Name
0       201   Image_Pic1  ./face_recog/celebrit1.jpg
1       202   Image_Pic2  ./face_recog/celebrit2.jpg
2       203   Image_Pic3  ./face_recog/celebrit3.jpg
3       204   Image_Pic4  ./face_recog/celebrit4.jpg
4       205   Image_Pic5  ./face_recog/celebrit5.jpg
5       206  Immage_Pic6      ./face_recog/pic3.jpeg
[False, False, False, False, False, True]


In [95]:
import pandas as pd
from PIL import Image, ImageDraw, ImageFont
import face_recognition
fnt = ImageFont.truetype("calibri.ttf", 60, encoding="unic")

f = pd.read_csv('./Data.csv')

print(f.to_string())
empno = f["Staff_ID"].tolist()
name = f["Name"].tolist()
filename = f["File Name"].tolist()
n = len(empno)
emp = []
emp_encod = []
ukwn= face_recognition.load_image_file("./pics&group/pic1.jpeg")
print(ukwn.shape)
ukwn_encod = face_recognition.face_encodings(ukwn)[0]
for i in range(n):
    emp.append(face_recognition.load_image_file(filename[i]))
    emp_encod.append(face_recognition.face_encodings(emp[i])[0])
    
found = face_recognition.compare_faces(emp_encod,ukwn_encod, tolerance = 0.4)    
print(found)
for i in range(n):
    if found[i]:
    
        left = 100
        bottom = ukwn.shape[0]
        pil_ukwn = Image.fromarray(ukwn)
        draw = ImageDraw.Draw(pil_ukwn)
        draw.text((left,bottom - 250), name[i], font=fnt, fill=(255,0,0))
        pil_ukwn.show()

   Staff_ID        Name                   File Name
0       201  Image_Pic1  ./face_recog/celebrit1.jpg
1       202  Image_Pic2  ./face_recog/celebrit2.jpg
2       203  Image_Pic3  ./face_recog/celebrit3.jpg
3       204  Image_Pic4  ./face_recog/celebrit4.jpg
4       205  Image_Pic5  ./face_recog/celebrit5.jpg
5       206  Image_Pic6      ./face_recog/pic3.jpeg
(1024, 769, 3)
[False, False, False, False, False, True]


## Attendance Recording in a File

In [99]:
import datetime
import pandas as pd
import face_recognition
f = pd.read_csv('./Data.csv')
print(f.to_string())
empno = f["Staff_ID"].tolist()
name = f["Name"].tolist()
filename = f["File Name"].tolist()
n = len(empno)
emp = []
emp_encod = []
ukwn= face_recognition.load_image_file("./pics&group/pic6.jpeg")
print(ukwn.shape)
ukwn_encod = face_recognition.face_encodings(ukwn)[0]
for i in range(n):
    emp.append(face_recognition.load_image_file(filename[i]))
    emp_encod.append(face_recognition.face_encodings(emp[i])[0])
    
found = face_recognition.compare_faces(emp_encod,ukwn_encod, tolerance = 0.4)    
print(found)
for i in range(n):
    if found[i]:
        x = str(datetime.datetime.now())
        attend = "\n"+str(empno[i])+' '+str(name[i]+' '+x)
        f = open("Attendance.txt", "a")
        f.write(attend)
        f.close()


   Staff_ID        Name                   File Name
0       201  Image_Pic1  ./face_recog/celebrit1.jpg
1       202  Image_Pic2  ./face_recog/celebrit2.jpg
2       203  Image_Pic3  ./face_recog/celebrit3.jpg
3       204  Image_Pic4  ./face_recog/celebrit4.jpg
4       205  Image_Pic5  ./face_recog/celebrit5.jpg
5       206  Image_Pic6      ./face_recog/pic3.jpeg
(1024, 1019, 3)
[False, False, False, False, False, False]


In [101]:
import cv2
camera = cv2.VideoCapture(0)
for i in range(10):
    return_value, image = camera.read()
    print(return_value, image.shape)
    cv2.imwrite('photo'+str(i)+'.png', image)
del(camera)

True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)
True (480, 640, 3)


In [102]:
import face_recognition
import cv2
from PIL import Image, ImageDraw, ImageFont
import sys
import pandas as pd
import datetime
import pygame
# Module 1 Reference Data Load Module
ef = pd.read_csv('./database/staff_data.csv')
empno = ef["Employee No"].tolist()
firstname = ef["First Name"].tolist()
lastname = ef["Last Name"].tolist()
photolocation = ef["Photo Location"].tolist()
audiolocation = ef["Audio Location"].tolist()
n = len(empno)
emp = []
emp_encod = []
audio = []
for i in range(n):
    emp.append(face_recognition.load_image_file(photolocation[i]))
    emp_encod.append(face_recognition.face_encodings(emp[i])[0])

ModuleNotFoundError: No module named 'pygame'